package com.unimelb.swen90017.rfo.util;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.unimelb.swen90017.rfo.pojo.po.*;
import com.unimelb.swen90017.rfo.pojo.vo.AssessmentVO;
import com.unimelb.swen90017.rfo.pojo.vo.GroupCommentVO;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class PdfReportGenerator {

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 18, Font.BOLD);
    private static final Font SUBTITLE_FONT = new Font(Font.HELVETICA, 14, Font.BOLD);
    private static final Font NORMAL_FONT = new Font(Font.HELVETICA, 10, Font.NORMAL);
    private static final Font BOLD_FONT = new Font(Font.HELVETICA, 10, Font.BOLD);
    private static final Font HEADER_FONT = new Font(Font.HELVETICA, 10, Font.BOLD, Color.WHITE);
    private static final Font FOOTER_FONT = new Font(Font.HELVETICA, 8, Font.ITALIC, Color.GRAY);

    public static byte[] generateIndividualReport(StudentPO student, ProjectPO project,
                                                   List<AssessmentVO> criteria,
                                                   List<MarkerBlock> markerBlocks,
                                                   BigDecimal finalScore) {
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            Document document = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(document, baos);
            document.open();

            Paragraph title = new Paragraph("Assessment Report", TITLE_FONT);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            document.add(new Paragraph("Student: " + student.getFirstName() + " " + student.getSurname()
                    + " (" + student.getStudentId() + ")", BOLD_FONT));
            document.add(new Paragraph("Project: " + project.getName(), NORMAL_FONT));
            document.add(new Paragraph("Date: " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd MMMM yyyy", Locale.ENGLISH)), NORMAL_FONT));
            document.add(Chunk.NEWLINE);

            BigDecimal maxScore = computeWeightedMax(criteria);
            Paragraph finalPara = new Paragraph("Final Mark: " + finalScore + " / " + maxScore, SUBTITLE_FONT);
            finalPara.setSpacingAfter(15);
            document.add(finalPara);

            for (MarkerBlock block : markerBlocks) {
                String totalLabel = block.totalScore != null ? block.totalScore.toString() : "-";
                Paragraph markerHeader = new Paragraph(
                        "Marker: " + block.markerName + " — Total: " + totalLabel, BOLD_FONT);
                markerHeader.setSpacingBefore(10);
                markerHeader.setSpacingAfter(5);
                document.add(markerHeader);

                Map<Long, MarkDetailPO> detailMap = block.details.stream()
                        .collect(Collectors.toMap(MarkDetailPO::getCriteriaId, d -> d, (a, b) -> a));
                document.add(buildScoreTable(criteria, detailMap));
            }

            document.add(Chunk.NEWLINE);
            Paragraph footer = new Paragraph("Generated by RapidFeedback", FOOTER_FONT);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            return baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate individual PDF report", e);
        }
    }

    public static class MarkerBlock {
        public final String markerName;
        public final BigDecimal totalScore;
        public final List<MarkDetailPO> details;

        public MarkerBlock(String markerName, BigDecimal totalScore, List<MarkDetailPO> details) {
            this.markerName = markerName;
            this.totalScore = totalScore;
            this.details = details;
        }
    }

    public static class IndividualSummaryRow {
        public final String studentName;
        public final String studentId;
        public final String markers;
        public final BigDecimal finalScore;
        public final Map<Long, BigDecimal> criteriaAvgScores;

        public IndividualSummaryRow(String studentName, String studentId, String markers,
                                     BigDecimal finalScore, Map<Long, BigDecimal> criteriaAvgScores) {
            this.studentName = studentName;
            this.studentId = studentId;
            this.markers = markers;
            this.finalScore = finalScore;
            this.criteriaAvgScores = criteriaAvgScores;
        }
    }

    /** One marker's per-student individual block for the student PDF. */
    public static class MarkerIndividualBlock {
        public final String markerName;
        public final BigDecimal individualTotal;  // mark_record.total_score
        public final BigDecimal groupScore;       // mark_record.group_score
        public final List<MarkDetailPO> details;  // this marker's per-criteria scores for this student

        public MarkerIndividualBlock(String markerName, BigDecimal individualTotal,
                                      BigDecimal groupScore, List<MarkDetailPO> details) {
            this.markerName = markerName;
            this.individualTotal = individualTotal;
            this.groupScore = groupScore;
            this.details = details;
        }
    }

    /** One row in the group-summary table (per group). */
    public static class GroupSummaryRowV2 {
        public final String groupName;
        public final String members;
        /** Average of per-student final_mark.final_score within the group. */
        public final BigDecimal finalScore;
        public final BigDecimal groupTotal;       // getGroupTotalScore
        public final Map<Long, BigDecimal> criteriaAvgScores; // all members x all markers in each criterion

        public GroupSummaryRowV2(String groupName, String members, BigDecimal finalScore,
                                  BigDecimal groupTotal, Map<Long, BigDecimal> criteriaAvgScores) {
            this.groupName = groupName;
            this.members = members;
            this.finalScore = finalScore;
            this.groupTotal = groupTotal;
            this.criteriaAvgScores = criteriaAvgScores;
        }
    }

    /** One row in the per-student section of a group-project summary report. */
    public static class IndividualInGroupSummaryRow {
        public final String studentName;
        public final String studentId;
        public final String groupName;
        public final String markers;
        /** Per-student final_mark.final_score keyed on (project_id, student_id, group_id). */
        public final BigDecimal finalScore;
        public final BigDecimal individualTotalAvg; // avg of mark_record.total_score across markers
        public final BigDecimal groupScoreAvg;      // avg of mark_record.group_score across markers
        public final Map<Long, BigDecimal> criteriaAvgScores; // cross-marker per-criteria avg

        public IndividualInGroupSummaryRow(String studentName, String studentId, String groupName,
                                            String markers, BigDecimal finalScore,
                                            BigDecimal individualTotalAvg,
                                            BigDecimal groupScoreAvg,
                                            Map<Long, BigDecimal> criteriaAvgScores) {
            this.studentName = studentName;
            this.studentId = studentId;
            this.groupName = groupName;
            this.markers = markers;
            this.finalScore = finalScore;
            this.individualTotalAvg = individualTotalAvg;
            this.groupScoreAvg = groupScoreAvg;
            this.criteriaAvgScores = criteriaAvgScores;
        }
    }

    public static byte[] generateIndividualProjectSummaryReport(ProjectPO project,
                                                                  List<AssessmentVO> criteria,
                                                                  List<IndividualSummaryRow> rows,
                                                                  BigDecimal projectAverageFinalScore) {
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            Document document = new Document(PageSize.A4.rotate(), 30, 30, 30, 30);
            PdfWriter.getInstance(document, baos);
            document.open();

            Paragraph title = new Paragraph("Project Summary Report", TITLE_FONT);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(10);
            document.add(title);

            BigDecimal maxScore = computeWeightedMax(criteria);

            document.add(new Paragraph("Project: " + project.getName(), BOLD_FONT));
            document.add(new Paragraph("Date: " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd MMMM yyyy", Locale.ENGLISH)), NORMAL_FONT));
            document.add(new Paragraph("Total students: " + rows.size(), NORMAL_FONT));
            String avgLabel = projectAverageFinalScore != null ? projectAverageFinalScore.toString() : "-";
            document.add(new Paragraph("Project Average Final Mark: " + avgLabel + " / " + maxScore, BOLD_FONT));
            document.add(Chunk.NEWLINE);

            int fixedCols = 4;
            int totalCols = fixedCols + criteria.size();
            float[] widths = new float[totalCols];
            widths[0] = 2.5f;
            widths[1] = 1.5f;
            widths[2] = 2.5f;
            widths[3] = 1f;
            for (int i = 0; i < criteria.size(); i++) widths[fixedCols + i] = 1.2f;
            PdfPTable table = new PdfPTable(widths);
            table.setWidthPercentage(100);
            table.setSpacingBefore(5);

            addHeaderCell(table, "Student");
            addHeaderCell(table, "Student ID");
            addHeaderCell(table, "Markers");
            addHeaderCell(table, "Final Mark");
            for (AssessmentVO c : criteria) {
                addHeaderCell(table, c.getName() + " (" + c.getWeighting() + "%)");
            }

            for (IndividualSummaryRow row : rows) {
                addCell(table, row.studentName, NORMAL_FONT);
                addCell(table, row.studentId != null ? row.studentId : "-", NORMAL_FONT);
                addCell(table, row.markers != null ? row.markers : "-", NORMAL_FONT);
                addCell(table, row.finalScore != null ? row.finalScore.toString() : "-", NORMAL_FONT);
                for (AssessmentVO c : criteria) {
                    BigDecimal s = row.criteriaAvgScores != null ? row.criteriaAvgScores.get(c.getCriteriaId()) : null;
                    addCell(table, s != null ? s.toString() : "-", NORMAL_FONT);
                }
            }
            document.add(table);

            document.add(Chunk.NEWLINE);
            Paragraph footer = new Paragraph("Generated by RapidFeedback", FOOTER_FONT);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            return baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate individual project summary PDF report", e);
        }
    }

    public static byte[] generateGroupProjectSummaryReport(ProjectPO project,
                                                             List<AssessmentVO> criteria,
                                                             List<GroupSummaryRowV2> groupRows,
                                                             List<IndividualInGroupSummaryRow> studentRows,
                                                             BigDecimal projectAverageFinalScore) {
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            Document document = new Document(PageSize.A4.rotate(), 30, 30, 30, 30);
            PdfWriter.getInstance(document, baos);
            document.open();

            Paragraph title = new Paragraph("Project Summary Report", TITLE_FONT);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(10);
            document.add(title);

            BigDecimal maxScore = computeWeightedMax(criteria);
            document.add(new Paragraph("Project: " + project.getName(), BOLD_FONT));
            document.add(new Paragraph("Date: " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd MMMM yyyy", Locale.ENGLISH)), NORMAL_FONT));
            document.add(new Paragraph("Total groups: " + groupRows.size(), NORMAL_FONT));
            document.add(new Paragraph("Total students: " + studentRows.size(), NORMAL_FONT));
            String avgLabel = projectAverageFinalScore != null ? projectAverageFinalScore.toString() : "-";
            document.add(new Paragraph("Project Average Final Mark: " + avgLabel + " / " + maxScore, BOLD_FONT));
            document.add(Chunk.NEWLINE);

            // Groups section
            Paragraph groupsHeader = new Paragraph("Groups", SUBTITLE_FONT);
            groupsHeader.setSpacingBefore(5);
            groupsHeader.setSpacingAfter(5);
            document.add(groupsHeader);

            int groupFixedCols = 4;
            int groupTotalCols = groupFixedCols + criteria.size();
            float[] groupWidths = new float[groupTotalCols];
            groupWidths[0] = 2f;
            groupWidths[1] = 4f;
            groupWidths[2] = 1.2f;
            groupWidths[3] = 1.2f;
            for (int i = 0; i < criteria.size(); i++) groupWidths[groupFixedCols + i] = 1.2f;
            PdfPTable groupTable = new PdfPTable(groupWidths);
            groupTable.setWidthPercentage(100);
            groupTable.setSpacingBefore(5);

            addHeaderCell(groupTable, "Group");
            addHeaderCell(groupTable, "Members");
            addHeaderCell(groupTable, "Final Mark Avg");
            addHeaderCell(groupTable, "Group Score Avg");
            for (AssessmentVO c : criteria) {
                addHeaderCell(groupTable, c.getName() + " (" + c.getWeighting() + "%)");
            }

            for (GroupSummaryRowV2 row : groupRows) {
                addCell(groupTable, row.groupName, NORMAL_FONT);
                addCell(groupTable, row.members != null ? row.members : "-", NORMAL_FONT);
                addCell(groupTable, row.finalScore != null ? row.finalScore.toString() : "-", NORMAL_FONT);
                addCell(groupTable,
                        row.groupTotal != null
                                ? row.groupTotal.setScale(2, java.math.RoundingMode.HALF_UP).toString()
                                : "-",
                        NORMAL_FONT);
                for (AssessmentVO c : criteria) {
                    BigDecimal s = row.criteriaAvgScores != null ? row.criteriaAvgScores.get(c.getCriteriaId()) : null;
                    addCell(groupTable, s != null ? s.toString() : "-", NORMAL_FONT);
                }
            }
            document.add(groupTable);

            // Students section
            Paragraph studentsHeader = new Paragraph("Students", SUBTITLE_FONT);
            studentsHeader.setSpacingBefore(15);
            studentsHeader.setSpacingAfter(5);
            document.add(studentsHeader);

            int stuFixedCols = 7;
            int stuTotalCols = stuFixedCols + criteria.size();
            float[] stuWidths = new float[stuTotalCols];
            stuWidths[0] = 2.5f;
            stuWidths[1] = 1.5f;
            stuWidths[2] = 2f;
            stuWidths[3] = 2.5f;
            stuWidths[4] = 1.2f;
            stuWidths[5] = 1.2f;
            stuWidths[6] = 1.2f;
            for (int i = 0; i < criteria.size(); i++) stuWidths[stuFixedCols + i] = 1.2f;
            PdfPTable stuTable = new PdfPTable(stuWidths);
            stuTable.setWidthPercentage(100);
            stuTable.setSpacingBefore(5);

            addHeaderCell(stuTable, "Student");
            addHeaderCell(stuTable, "Student ID");
            addHeaderCell(stuTable, "Group");
            addHeaderCell(stuTable, "Markers");
            addHeaderCell(stuTable, "Final Mark");
            addHeaderCell(stuTable, "Individual Avg");
            addHeaderCell(stuTable, "Group Score Avg");
            for (AssessmentVO c : criteria) {
                addHeaderCell(stuTable, c.getName() + " (" + c.getWeighting() + "%)");
            }

            for (IndividualInGroupSummaryRow row : studentRows) {
                addCell(stuTable, row.studentName != null ? row.studentName : "-", NORMAL_FONT);
                addCell(stuTable, row.studentId != null ? row.studentId : "-", NORMAL_FONT);
                addCell(stuTable, row.groupName != null ? row.groupName : "-", NORMAL_FONT);
                addCell(stuTable, row.markers != null ? row.markers : "-", NORMAL_FONT);
                addCell(stuTable, row.finalScore != null ? row.finalScore.toString() : "-", NORMAL_FONT);
                addCell(stuTable, row.individualTotalAvg != null ? row.individualTotalAvg.toString() : "-", NORMAL_FONT);
                addCell(stuTable, row.groupScoreAvg != null ? row.groupScoreAvg.toString() : "-", NORMAL_FONT);
                for (AssessmentVO c : criteria) {
                    BigDecimal s = row.criteriaAvgScores != null ? row.criteriaAvgScores.get(c.getCriteriaId()) : null;
                    addCell(stuTable, s != null ? s.toString() : "-", NORMAL_FONT);
                }
            }
            document.add(stuTable);

            document.add(Chunk.NEWLINE);
            Paragraph footer = new Paragraph("Generated by RapidFeedback", FOOTER_FONT);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            return baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate group project summary PDF report", e);
        }
    }

    public static byte[] generateGroupReport(StudentPO student,
                                              ProjectGroupPO group,
                                              List<StudentPO> members,
                                              ProjectPO project,
                                              List<AssessmentVO> criteria,
                                              List<MarkerIndividualBlock> markerBlocks,
                                              BigDecimal groupTotalScore,
                                              List<GroupCommentVO> groupComments,
                                              BigDecimal finalScore) {
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            Document document = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(document, baos);
            document.open();

            // Title
            Paragraph title = new Paragraph("Group Assessment Report", TITLE_FONT);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Student + group info
            document.add(new Paragraph("Student: " + student.getFirstName() + " " + student.getSurname()
                    + " (" + student.getStudentId() + ")", BOLD_FONT));
            document.add(new Paragraph("Group: " + group.getGroupName(), BOLD_FONT));
            String memberNames = members.stream()
                    .map(s -> s.getFirstName() + " " + s.getSurname())
                    .collect(Collectors.joining(", "));
            document.add(new Paragraph("Members: " + memberNames, NORMAL_FONT));
            document.add(new Paragraph("Project: " + project.getName(), NORMAL_FONT));
            document.add(new Paragraph("Date: " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd MMMM yyyy", Locale.ENGLISH)), NORMAL_FONT));
            document.add(Chunk.NEWLINE);

            BigDecimal maxScore = computeWeightedMax(criteria);

            // Final Mark (group-level)
            String finalLabel = finalScore != null ? finalScore.toString() : "-";
            Paragraph finalPara = new Paragraph("Final Mark (Group): " + finalLabel + " / " + maxScore, SUBTITLE_FONT);
            finalPara.setSpacingAfter(15);
            document.add(finalPara);

            // Individual Scores (this student only)
            Paragraph individualHeader = new Paragraph("Individual Scores", SUBTITLE_FONT);
            individualHeader.setSpacingBefore(5);
            individualHeader.setSpacingAfter(5);
            document.add(individualHeader);

            if (markerBlocks == null || markerBlocks.isEmpty()) {
                document.add(new Paragraph("No individual scores have been recorded for this student.", NORMAL_FONT));
            } else {
                for (MarkerIndividualBlock block : markerBlocks) {
                    String indivTotal = block.individualTotal != null ? block.individualTotal.toString() : "-";
                    String gScore = block.groupScore != null ? block.groupScore.toString() : "-";
                    Paragraph markerHeader = new Paragraph(
                            "Marker: " + block.markerName + " — Individual Total: " + indivTotal
                                    + "  |  Group Score: " + gScore, BOLD_FONT);
                    markerHeader.setSpacingBefore(10);
                    markerHeader.setSpacingAfter(5);
                    document.add(markerHeader);

                    Map<Long, MarkDetailPO> detailMap = block.details != null
                            ? block.details.stream().collect(Collectors.toMap(
                                    MarkDetailPO::getCriteriaId, d -> d, (a, b) -> a))
                            : java.util.Collections.emptyMap();
                    document.add(buildScoreTable(criteria, detailMap));
                }
            }

            // Group Assessment section
            Paragraph groupHeader = new Paragraph("Group Assessment", SUBTITLE_FONT);
            groupHeader.setSpacingBefore(15);
            groupHeader.setSpacingAfter(5);
            document.add(groupHeader);

            String gTotal = groupTotalScore != null
                    ? groupTotalScore.setScale(2, java.math.RoundingMode.HALF_UP).toString()
                    : "-";
            document.add(new Paragraph("Group Score Avg: " + gTotal + " / " + maxScore, BOLD_FONT));

            if (groupComments == null || groupComments.isEmpty()) {
                document.add(new Paragraph("Group Comment: -", NORMAL_FONT));
            } else {
                Paragraph commentsLabel = new Paragraph("Group Comments:", BOLD_FONT);
                commentsLabel.setSpacingBefore(5);
                document.add(commentsLabel);
                for (GroupCommentVO c : groupComments) {
                    String markerLabel = c.getMarkerName() != null ? c.getMarkerName() : "-";
                    String commentText = c.getComment() != null && !c.getComment().isBlank()
                            ? c.getComment() : "-";
                    document.add(new Paragraph("  • " + markerLabel + ": " + commentText, NORMAL_FONT));
                }
            }

            // Footer
            document.add(Chunk.NEWLINE);
            Paragraph footer = new Paragraph("Generated by RapidFeedback", FOOTER_FONT);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            return baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate group PDF report", e);
        }
    }

    /**
     * Weighted maximum score = Σ (maximum_mark × weighting / 100) across criteria,
     * rounded HALF_UP to 2 decimal places. BigDecimal all the way to avoid the
     * binary-float drift you get from `int * 0.01 * int`.
     */
    private static BigDecimal computeWeightedMax(List<AssessmentVO> criteria) {
        if (criteria == null || criteria.isEmpty()) {
            return BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
        }
        BigDecimal sum = BigDecimal.ZERO;
        BigDecimal hundred = BigDecimal.valueOf(100);
        for (AssessmentVO c : criteria) {
            BigDecimal part = BigDecimal.valueOf(c.getMaxMark())
                    .multiply(BigDecimal.valueOf(c.getWeighting()))
                    .divide(hundred, 4, RoundingMode.HALF_UP);
            sum = sum.add(part);
        }
        return sum.setScale(2, RoundingMode.HALF_UP);
    }

    private static PdfPTable buildScoreTable(List<AssessmentVO> criteria,
                                              Map<Long, MarkDetailPO> detailMap) {
        PdfPTable table = new PdfPTable(new float[]{4f, 1.2f, 1f, 4f});
        table.setWidthPercentage(100);
        table.setSpacingBefore(5);

        // Header
        addHeaderCell(table, "Criteria");
        addHeaderCell(table, "Score");
        addHeaderCell(table, "Max");
        addHeaderCell(table, "Comment");

        // Rows
        for (AssessmentVO c : criteria) {
            MarkDetailPO detail = detailMap.get(c.getCriteriaId());
            String criteriaLabel = c.getName() + " (" + c.getWeighting() + "%)";
            String score = detail != null && detail.getScore() != null ? detail.getScore().toString() : "-";
            String max = String.valueOf(c.getMaxMark());
            String comment = detail != null && detail.getComment() != null && !detail.getComment().isBlank()
                    ? detail.getComment() : "-";

            addCell(table, criteriaLabel, NORMAL_FONT);
            addCell(table, score, NORMAL_FONT);
            addCell(table, max, NORMAL_FONT);
            addCell(table, comment, NORMAL_FONT);
        }

        return table;
    }

    private static void addHeaderCell(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, HEADER_FONT));
        cell.setBackgroundColor(new Color(51, 51, 51));
        cell.setPadding(6);
        table.addCell(cell);
    }

    private static void addCell(PdfPTable table, String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setPadding(5);
        table.addCell(cell);
    }
}
